### PR TITLE
Use new modeling repository

### LINKED ISSUE #10: Test Confidentiality Analysis with Modeling Repository
Test the analysis with the [modeling repo](https://github.com/PalladioSimulator/Palladio-Addons-DataFlowConfidentiality-Metamodel), then update the eclipse installation file in the GitHub repository.

### PR DESCRIPTION
**Pull request by Entenwilli**
This PR add some documentation and an **install file** for the new modelling repository outlined in #10. In my current testing, i have found no issues using the new modelling repository, so i think we can begin using the new model.

As this PR includes the fixes from #22, this PR should be merged after that PR is merged. I will fast-forward this branch, as soon as that PR is merged

This PR closes #10, as i haven't found any issues in the tests and analysis with the new repository

### CODE REVIEW

**Comment by sebinside** [comment]
@Entenwilli I merged #22, please rebase this PR.

**Comment by sebinside** [comment]
This PR seems to contain some parts of #26. Should it not contain only the change to the readme and the dependency file?

Regarding the new dependency file, you can overwrite the old one. Please also include the OCL dependencies like `OCL Examples and Editors SDK` as they can be required by Palladio to function properly. Also, please include the `CDO Debug Utils` as these are often used by developers and the `.p2f` file clearly is for developers :)

**Comment by Entenwilli** [comment]
Okay, after screwing up the rebase, i have now updated the dependencies file with the additonal OCL Dependencies from the Eclipse OCL updatesite. Furthermore, i have added the `CDO Debug Utils` for easier debugging. This PR should be fine now

**Comment by Entenwilli** [comment]
@majuwa  Yesterday we spoke about the missing JUnit dependencies. 
After looking around, i think the errors in the manifest are a configuration issue, the junit dependencies should be listed under "Imported Packages" and not "Required Plug-ins". The JUnit dependencies should be present in every Eclipse Installation, so we don't need to install anything here

**Comment by majuwa** [comment]
> @majuwa Yesterday we spoke about the missing JUnit dependencies. After looking around, i think the errors in the manifest are a configuration issue, the junit dependencies should be listed under "Imported Packages" and not "Required Plug-ins". The JUnit dependencies should be present in every Eclipse Installation, so we don't need to install anything here

@Entenwilli that's great. We could then change it for the tests projects. Have you already tested it also with the maven build?

**Comment by Entenwilli** [comment]
> > @majuwa Yesterday we spoke about the missing JUnit dependencies. After looking around, i think the errors in the manifest are a configuration issue, the junit dependencies should be listed under "Imported Packages" and not "Required Plug-ins". The JUnit dependencies should be present in every Eclipse Installation, so we don't need to install anything here
> 
> @Entenwilli that's great. We could then change it for the tests projects. Have you already tested it also with the maven build?

@majuwa Yes i tested it, sadly tycho is not able to resolve the dependency despite junit being included in normal Eclipse installations. Should i commit the changed files, so someone else more familiar with tycho and Eclipse can look over it?

**Comment by majuwa** [comment]
@Entenwilli  ok, that's strange. For one of my projects your solutions worked. Is there maybe a problem with the JUnit version. For maven, you might need an older JUnit version. You can take a look at [my solution](https://github.com/FluidTrust/Palladio-Addons-ContextConfidentiality-Metamodel/commit/58b0862e03438c65785b36672ec86abb30e2bacf). Maybe, you can find some differences to yours and identify why it works in that repository and this one not. In any case, please commit your solution and then we can also take a look at it.

**Comment by Entenwilli** [comment]
@sebinside @majuwa After changing the version in the manifest to a lower one as well, it works now. That means, that we can review and merge this PR as well. No additional dependencies are required as all supported Eclipse Installations come with a working version of JUnit5

**Comment by sebinside** [comment]
@Entenwilli I will test the new version against `2022-12` next week and then merge the PR.

**Comment by sebinside** [comment]
I tested the install file both in `2022-09` and `2022-12` without success. The confidentiality editor and UI packages had a dependency on the indirections project. Even after installing these manually, I was not able to install all required items from the file. It's strange that this problem did not occur in your testing but it can of course also be totally my fault.

After wasting a complete morning on this, I pass this issue to @Nicolas-Boltz and @majuwa

**Comment by Entenwilli** [comment]
Hmm.... I looked into the exported .xml file and it seems that eclipse does not export Update Sites, from which no software was explicitly installed. This means that it does not save the Update Site for Palladio Indirections, when you install it as an Dependency of the modelling project.

I was not aware that Eclipse does that... This probably means that I need to explicitly install the dependencies in my working installation and export it again, hoping that the Update Sites show up in the exported file

**Comment by sebinside** [comment]
Tested with `2022-12`:
```
Your original request has been modified.
  "OCL Classic SDK: Ecore/UML Parsers,Evaluator,Edit" is already installed, so an update will be performed instead.
Cannot complete the install because one or more required items could not be found.
  Software being installed: Palladio Component Model 5.1.0.202212190152 (org.palladiosimulator.pcm.feature.feature.group 5.1.0.202212190152)
  Missing requirement: org.palladiosimulator.commons.stoex 5.1.0.202212190110 (org.palladiosimulator.commons.stoex 5.1.0.202212190110) requires 'osgi.bundle; org.eclipse.xtend.standalone 2.8.2' but it could not be found
  Cannot satisfy dependency:
    From: PalladioComponentModel Model 5.1.0.202212190152 (org.palladiosimulator.pcm 5.1.0.202212190152)
    To: osgi.bundle; org.palladiosimulator.commons.stoex 5.0.0
  Cannot satisfy dependency:
    From: Palladio Component Model 5.1.0.202212190152 (org.palladiosimulator.pcm.feature.feature.group 5.1.0.202212190152)
    To: org.eclipse.equinox.p2.iu; org.palladiosimulator.pcm 4.0.0
```

**Comment by Entenwilli** [comment]
It seems Eclipse cannot find a repository for Xtend/Xtext dependencies. The most recent commit should include the Update Site and dependency in it.

**Review by sebinside — APPROVED** [review]
Looks like we have a working version :)

**Pull request merged**
